//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//
// ПРИМІТКА: поля RunAtStartup, MinimizeToTray, AutoUpdateLocalization,
// LastLocalizationToast, LastLiaToast, LastAppToast, LastToastTimestampUtc
// додані вручну (CLI MSBuild не запускає SettingsSingleFileGenerator — це
// Visual Studio Design-Time-only задача). При наступному відкритті у VS
// з секції Settings цей файл буде автоматично регенеровано з Settings.settings,
// поля збережуться (значення за замовчуванням узгоджені між .settings і .cs).
//------------------------------------------------------------------------------

namespace SCLOCVerse {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAppVersion {
            get {
                return ((string)(this["LastAppVersion"]));
            }
            set {
                this["LastAppVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameFolder {
            get {
                return ((string)(this["GameFolder"]));
            }
            set {
                this["GameFolder"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stable")]
        public string UpdateChannel {
            get {
                return ((string)(this["UpdateChannel"]));
            }
            set {
                this["UpdateChannel"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UpgradeRequired {
            get {
                return ((bool)(this["UpgradeRequired"]));
            }
            set {
                this["UpgradeRequired"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double HangarOverlayX {
            get {
                return ((double)(this["HangarOverlayX"]));
            }
            set {
                this["HangarOverlayX"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public double HangarOverlayY {
            get {
                return ((double)(this["HangarOverlayY"]));
            }
            set {
                this["HangarOverlayY"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.6")]
        public double HangarOverlayScale {
            get {
                return ((double)(this["HangarOverlayScale"]));
            }
            set {
                this["HangarOverlayScale"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.92")]
        public double HangarOverlayOpacity {
            get {
                return ((double)(this["HangarOverlayOpacity"]));
            }
            set {
                this["HangarOverlayOpacity"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int HangarOverlayMode {
            get {
                return ((int)(this["HangarOverlayMode"]));
            }
            set {
                this["HangarOverlayMode"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long HangarCycleStartOverride {
            get {
                return ((long)(this["HangarCycleStartOverride"]));
            }
            set {
                this["HangarCycleStartOverride"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("RawInput")]
        public string InputSystemBackend {
            get {
                return ((string)(this["InputSystemBackend"]));
            }
            set {
                this["InputSystemBackend"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InputSystemDiagnostics {
            get {
                return ((bool)(this["InputSystemDiagnostics"]));
            }
            set {
                this["InputSystemDiagnostics"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RunAtStartup {
            get {
                return ((bool)(this["RunAtStartup"]));
            }
            set {
                this["RunAtStartup"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MinimizeToTray {
            get {
                return ((bool)(this["MinimizeToTray"]));
            }
            set {
                this["MinimizeToTray"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoUpdateLocalization {
            get {
                return ((bool)(this["AutoUpdateLocalization"]));
            }
            set {
                this["AutoUpdateLocalization"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AdvancedDiagnostics {
            get {
                return ((bool)(this["AdvancedDiagnostics"]));
            }
            set {
                this["AdvancedDiagnostics"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastLocalizationToast {
            get {
                return ((string)(this["LastLocalizationToast"]));
            }
            set {
                this["LastLocalizationToast"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastLiaToast {
            get {
                return ((string)(this["LastLiaToast"]));
            }
            set {
                this["LastLiaToast"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastAppToast {
            get {
                return ((string)(this["LastAppToast"]));
            }
            set {
                this["LastAppToast"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastToastTimestampUtc {
            get {
                return ((string)(this["LastToastTimestampUtc"]));
            }
            set {
                this["LastToastTimestampUtc"] = value;
            }
        }

        // ===== Anti-AFK =====

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AntiAfkEnabled {
            get {
                return ((bool)(this["AntiAfkEnabled"]));
            }
            set {
                this["AntiAfkEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#4CAF50")]
        public string AntiAfkIndicatorColor {
            get {
                return ((string)(this["AntiAfkIndicatorColor"]));
            }
            set {
                this["AntiAfkIndicatorColor"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TopRight")]
        public string AntiAfkIndicatorPosition {
            get {
                return ((string)(this["AntiAfkIndicatorPosition"]));
            }
            set {
                this["AntiAfkIndicatorPosition"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double AntiAfkIndicatorSize {
            get {
                return ((double)(this["AntiAfkIndicatorSize"]));
            }
            set {
                this["AntiAfkIndicatorSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Pulse")]
        public string AntiAfkIndicatorAnimation {
            get {
                return ((string)(this["AntiAfkIndicatorAnimation"]));
            }
            set {
                this["AntiAfkIndicatorAnimation"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Running")]
        public string AntiAfkIndicatorMode {
            get {
                return ((string)(this["AntiAfkIndicatorMode"]));
            }
            set {
                this["AntiAfkIndicatorMode"] = value;
            }
        }

        // ===== Auto Key =====

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AutoKeyEnabled {
            get {
                return ((bool)(this["AutoKeyEnabled"]));
            }
            set {
                this["AutoKeyEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Oem4")]
        public string AutoKeyActionKey {
            get {
                return ((string)(this["AutoKeyActionKey"]));
            }
            set {
                this["AutoKeyActionKey"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int AutoKeyIntervalMs {
            get {
                return ((int)(this["AutoKeyIntervalMs"]));
            }
            set {
                this["AutoKeyIntervalMs"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MiningEnabled {
            get {
                return ((bool)(this["MiningEnabled"]));
            }
            set {
                this["MiningEnabled"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int MiningCycleIntervalMs {
            get {
                return ((int)(this["MiningCycleIntervalMs"]));
            }
            set {
                this["MiningCycleIntervalMs"] = value;
            }
        }
    }
}
